// Fill out your copyright notice in the Description page of Project Settings.

#include "ThrowNoiseBomb.h"
#include "AbilitySystemComponent.h"
#include "AbilitySystemBlueprintLibrary.h"
#include "Components/SphereComponent.h"
#include "Components/StaticMeshComponent.h"
#include "GameFramework/ProjectileMovementComponent.h"
#include "SzComponents/NoiseComponent.h"
#include "Kismet/GameplayStatics.h"
#include "TimerManager.h"
#include "Log/TPTLog.h"

AThrowNoiseBomb::AThrowNoiseBomb()
{
    PrimaryActorTick.bCanEverTick = false;

    // УцЕЙ ФФЦїГЭЦЎ (ЗчЦЎ)
    CollisionComponent = CreateDefaultSubobject<USphereComponent>(TEXT("CollisionComponent"));
    CollisionComponent->InitSphereRadius(10.0f);
    //CollisionComponent->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);
    CollisionComponent->SetCollisionProfileName(TEXT("Projectile"));
    CollisionComponent->SetNotifyRigidBodyCollision(true); // Hit РЬКЅЦЎ Л§МК

    // ЗчЦЎЗЮ МГСЄ
    RootComponent = CollisionComponent;

    // ИоНУ ФФЦїГЭЦЎ (УцЕЙРК CollisionComponentАЁ ДуДч)
    MeshComponent = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("MeshComponent"));
    MeshComponent->SetupAttachment(CollisionComponent);
    MeshComponent->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    MeshComponent->SetRelativeLocation(FVector::ZeroVector);

    // ХѕЛчУМ РЬЕП ФФЦїГЭЦЎ
    ProjectileMovementComponent = CreateDefaultSubobject<UProjectileMovementComponent>(TEXT("ProjectileMovementComponent"));
    ProjectileMovementComponent->UpdatedComponent = CollisionComponent;
    ProjectileMovementComponent->InitialSpeed = 1200.0f;
    ProjectileMovementComponent->MaxSpeed = 2000.0f;
    ProjectileMovementComponent->bRotationFollowsVelocity = true;
    ProjectileMovementComponent->bShouldBounce = false;
    ProjectileMovementComponent->ProjectileGravityScale = 1.0f;

    // МвРН ФФЦїГЭЦЎ
    NoiseComponent = CreateDefaultSubobject<UNoiseComponent>(TEXT("NoiseComponent"));
}

void AThrowNoiseBomb::BeginPlay()
{
    Super::BeginPlay();

    // Hit РЬКЅЦЎ ЙйРЮЕљ
    if (CollisionComponent)
    {
        CollisionComponent->OnComponentHit.AddDynamic(this, &AThrowNoiseBomb::OnHit);
    }
}

void AThrowNoiseBomb::OnHit(UPrimitiveComponent* HitComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, FVector NormalImpulse, const FHitResult& Hit)
{
    // РкБт РкНХРЬГЊ МвРЏРкПЭРЧ УцЕЙРК ЙЋНУ
    if (OtherActor && OtherActor != this && OtherActor != GetOwner())
    {
        ExplodeAndMakeNoise();
    }
}

void AThrowNoiseBomb::InvokeGameplayCue()
{
    APlayerController* PC = GetWorld()->GetFirstPlayerController();
    if (PC && PC->GetPawn())
    {
        AActor* TargetActor = PC->GetPawn();
        UAbilitySystemComponent* TargetASC = UAbilitySystemBlueprintLibrary::GetAbilitySystemComponent(TargetActor);

        if (TargetASC)
        {
            FGameplayCueParameters Param;
            Param.SourceObject = this;
            Param.Instigator = TargetActor;
            Param.Location = GetActorLocation();
            TargetASC->ExecuteGameplayCue(GameplayCueTag, Param);
        }
    }
}

void AThrowNoiseBomb::ExplodeAndMakeNoise()
{
    // ХѕЛчУМ РЬЕП СЄСі
    if (ProjectileMovementComponent)
    {
        ProjectileMovementComponent->StopMovementImmediately();
        ProjectileMovementComponent->Deactivate();
    }

    InvokeGameplayCue();

    // МвРН НУРл
    if (NoiseComponent)
    {
        NoiseComponent->StartNoise();
    }

    // РЯСЄ НУАЃ ШФ ОзХЭ ЦФБЋ (МвРНРЬ ГЁГ­ ШФ)
    FTimerHandle DestroyTimer;
    if (GetWorld())
    {
        GetWorld()->GetTimerManager().SetTimer(DestroyTimer, [this]()
            {
                NoiseComponent->StopNoise();
                Destroy();
            }, NoiseDuration, false); // МвРНРЬ УцКаШї СіМгЕШ ШФ ЦФБЋ
    }
}
