// Fill out your copyright notice in the Description page of Project Settings.


#include "GM_PhantomTwins.h"

#include "PhantomTwinsInstance.h"
#include "Kismet/GameplayStatics.h"
#include "Blueprint/UserWidget.h"
#include "GameFramework/PlayerStart.h"
#include "GameFramework/PlayerState.h"
#include "OutGame/SaveGame/TPTSaveGameData.h"


#include "Kismet/KismetSystemLibrary.h"


void AGM_PhantomTwins::BeginPlay()
{
    Super::BeginPlay();
    UPhantomTwinsInstance* GameInstance = GetGameInstance<UPhantomTwinsInstance>();
    if (GameInstance && GameInstance->bIsRestartingLevel)
    {
        bShouldOverrideSpawns = true;
        OverrideSpawnDatas = GameInstance->RestartPlayerDatas;

        // Listen Server ИҜ°жҝЎјӯ јӯ№ц ЗГ·№АМҫо(ИЈҪәЖ®)ёё °ӯБҰ ё®ҪәЖщ
        //for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
        //{
        //    APlayerController* PC = Cast<APlayerController>(It->Get());
        //    if (PC && PC->IsLocalController() && GetNetMode() == NM_ListenServer)
        //    {
        //        // ұвБё Pawn БҰ°Е
        //        if (APawn* OldPawn = PC->GetPawn())
        //        {
        //            OldPawn->Destroy();
        //        }

        //        // јӯ№ц ЗГ·№АМҫоАЗ PlayerIDҙВ "Host"·О °ӯБҰ
        //        FString PlayerID = TEXT("Host");
        //        const FPlayerSaveData* FoundData = OverrideSpawnDatas.FindByPredicate(
        //            [&](const FPlayerSaveData& Data) { return Data.PlayerID == PlayerID; });

        //        if (FoundData)
        //        {
        //            // ҝшЗПҙВ Pawn Е¬·ЎҪә·О Spawn (DefaultPawnClass өо)
        //            APawn* NewPawn = GetWorld()->SpawnActor<APawn>(
        //                DefaultPawnClass, // ЗБ·ОБ§Ж®ҝЎ ёВҙВ PawnClass·О ұіГј
        //                FoundData->PlayerLocation,
        //                FoundData->PlayerRotation
        //            );
        //            if (NewPawn)
        //            {
        //                PC->Possess(NewPawn);
        //                UE_LOG(LogTemp, Warning, TEXT("[SERVER RESPAWN] Host player respawned at %s"), *FoundData->PlayerLocation.ToString());
        //            }
        //        }
        //        else
        //        {
        //            UE_LOG(LogTemp, Warning, TEXT("[SERVER RESPAWN] Host player: No matching save data!"));
        //        }
        //    }
        //}

        // ЗГ·ЎұЧёҰ №ЭөеҪГ ҙЩҪГ ІЁБаҫЯ ҙЩАҪ ёК ·ОөеҝЎ ҝөЗвА» БЦБц ҫКҪАҙПҙЩ.
        GameInstance->bIsRestartingLevel = false;
    }
}


void AGM_PhantomTwins::PostLogin(APlayerController* NewPlayer)
{
    Super::PostLogin(NewPlayer);

    TotalPlayerCount++;
}

void AGM_PhantomTwins::NotifyPlayerDied(AController* DeadPlayer, bool isDead)
{
    if(isDead)
        DeadPlayerCount++;
    else
        DeadPlayerCount--;

    if (DeadPlayerCount >= TotalPlayerCount)
    {
        RestartLevelWithDelay(3.0f);
    }
}

void AGM_PhantomTwins::S2A_ShowFadeUI_Implementation()
{
    for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
    {
        if (APlayerController* PC = It->Get())
        {
            if (PC->IsLocalController())
            {
                if (FadeUI)
                {
                    FadeUI->AddToViewport();
                }
            }
        }
    }
}

void AGM_PhantomTwins::RestartLevelWithDelay(float Delay)
{
    S2A_ShowFadeUI();

    // GameInstanceҝЎ ЗцАз ЗГ·№АМҫо А§ДЎ БӨәёёҰ АъАе
    UPhantomTwinsInstance* GameInstance = GetGameInstance<UPhantomTwinsInstance>();
    if (GameInstance)
    {
        // 1. АзҪГАЫ ЗГ·ЎұЧёҰ ДС°н, АМАь өҘАМЕНёҰ әсҝуҙПҙЩ.
        GameInstance->bIsRestartingLevel = true;
        GameInstance->RestartPlayerDatas.Empty();

        // 2. ЗцАз ёрөз ЗГ·№АМҫоёҰ јшИёЗПёз А§ДЎёҰ АъАеЗХҙПҙЩ.
        for (FConstPlayerControllerIterator It = GetWorld()->GetPlayerControllerIterator(); It; ++It)
        {
            AController* Controller = It->Get();
            if (Controller && Controller->PlayerState && Controller->GetPawn())
            {
                FPlayerSaveData RestartData;

                FString PlayerID;
                // јӯ№ц ЗГ·№АМҫо(ИЈҪәЖ®)¶уёй №«Б¶°З "Host"·О АъАе
                if (Controller->IsLocalController() && GetNetMode() == NM_ListenServer)
                    PlayerID = TEXT("Host");
                else if (Controller->PlayerState->GetUniqueId().IsValid())
                    PlayerID = Controller->PlayerState->GetUniqueId().ToString();
                else
                    PlayerID = Controller->PlayerState->GetPlayerName();

                RestartData.PlayerID = PlayerID;
                RestartData.PlayerLocation = Controller->GetPawn()->GetActorLocation();
                RestartData.PlayerRotation = Controller->GetPawn()->GetActorRotation();

                // ·ОұЧ·О И®АО
                UE_LOG(LogTemp, Warning, TEXT("[SAVE] PlayerID: %s, Location: %s"), *RestartData.PlayerID, *RestartData.PlayerLocation.ToString());

                GameInstance->RestartPlayerDatas.Add(RestartData);
            }
        }

    }

    FTimerHandle TimerHandle;
    GetWorldTimerManager().SetTimer(TimerHandle, [this]()
        {
            FString MapName = GetWorld()->GetOutermost()->GetName();
            FString LevelPathWithListen = MapName + TEXT("?listen");
            GetWorld()->ServerTravel(LevelPathWithListen, false);
        }, Delay, false);
}

AActor* AGM_PhantomTwins::FindPlayerStart_Implementation(AController* Player, const FString& IncomingName)
{
    UKismetSystemLibrary::PrintString(GetWorld(), FString::Printf(TEXT("GM ptr: %p"), this), true, true, FLinearColor::Red, 5.0f);
    if (bShouldOverrideSpawns && Player)
    {
		UKismetSystemLibrary::PrintString(GetWorld(), FString::Printf(TEXT("FindPlayerStart_Implementation: [FindPlayerStart_Implementation] Player: %s, IncomingName: %s"), *Player->GetName(), *IncomingName), true, true, FLinearColor::Red, 5.0f);
        UKismetSystemLibrary::PrintString(GetWorld(), FString::Printf(TEXT("FindPlayerStart_Implementation: [2222222222222222222222222222] bShouldOverrideSpawns is %d or %f is null"), bShouldOverrideSpawns, Player), true, true, FLinearColor::Red, 5.0f);

        FString PlayerId;
        if (Player->PlayerState && Player->PlayerState->GetUniqueId().IsValid())
            PlayerId = Player->PlayerState->GetUniqueId().ToString();
        else if (Player->IsLocalController() && GetNetMode() == NM_ListenServer)
            PlayerId = TEXT("Host");
        else
            PlayerId = TEXT("Unknown");

        UE_LOG(LogTemp, Warning, TEXT("[RESPAWN] PlayerID: %s"), *PlayerId);

        const FPlayerSaveData* FoundData = OverrideSpawnDatas.FindByPredicate(
            [&](const FPlayerSaveData& Data) { return Data.PlayerID == PlayerId; });

        if (FoundData)
        {
            UE_LOG(LogTemp, Warning, TEXT("[RESPAWN] FoundData Location: %s"), *FoundData->PlayerLocation.ToString());
            FActorSpawnParameters SpawnParams;
            SpawnParams.SpawnCollisionHandlingOverride = ESpawnActorCollisionHandlingMethod::AlwaysSpawn;
            APlayerStart* TempPlayerStart = GetWorld()->SpawnActor<APlayerStart>(
                FoundData->PlayerLocation, FoundData->PlayerRotation, SpawnParams);

            UE_LOG(LogTemp, Log, TEXT("Player %s is restarting at saved location."), *PlayerId);
            return TempPlayerStart;
        }
        else
        {
            UE_LOG(LogTemp, Warning, TEXT("[RESPAWN] No matching data found for PlayerID: %s!"), *PlayerId);
        }
    }
    else
    {
		UKismetSystemLibrary::PrintString(GetWorld(), FString::Printf(TEXT("FindPlayerStart_Implementation: [FindPlayerStart_Implementation] bShouldOverrideSpawns is %d or %f is null"), bShouldOverrideSpawns, Player), true, true, FLinearColor::Red, 5.0f);
        if (!Player)
			UE_LOG(LogTemp, Warning, TEXT("[FindPlayerStart_Implementation] Player3333333333333333333333333333333333333333333333333333"));
    	UE_LOG(LogTemp, Warning, TEXT("[FindPlayerStart_Implementation] Fail!"));
    }

    return Super::FindPlayerStart_Implementation(Player, IncomingName);
}